#!/bin/bash

function showhelp {
   echo -e "art2bib (babibtex) 0.2"
   echo -e "Bash bibtex generator for article and (scientific) literature"
   echo -e "It works with doi, isbn, arxiv and pmid"
   echo -e "art2bib [TYPE] [REFERENCE]"
   echo -e "\tTypes:"
   echo -e "\td,doi\tREFERENCE\tDOI reference format: 10.1016%2Fj.mechrescom.2008.08.009"
   echo -e "\ti,isbn\tREFERENCE\tISBN reference format: 0323030645"
   echo -e "\ta,arxiv\tREFERENCE\tArXiv reference format: 1810.03911"
   echo -e "\tp,pmid\tREFERENCE\tPMID reference format: 329010"
}
TEMP=$(getopt -o ":d:i:a:p:"  --long "doi:,isbn:,arxiv:,pmid:" -- "$@")
while true ; do
  case "$1" in
    d|doi)	
       wget -qO- "https://www.doi2bib.org/doi2bib?id=$2"; 
       echo "";
       exit 1;;
    i|isbn)	 
       wget -qO- --post-data="isbn=$2" https://bibtex.chimbori.com/isbn-bibtex \
       	  | sed  '/URL/d' \
	  | sed 'x;${s/,$//;p;x;};1d'; 
	echo "";
	exit 1;;	
    a|arxiv)	
       wget -qO - "https://arxiv2bibtex.org/?q=$2+&format=biblatex" \
	  | sed -n '/<div id=.biblatex.>/,/<.textarea>/p' \
	  | sed -n '/@/,$p' \
	  | sed 's/<.textarea>//;x;${s/,$//;p;x;};1d';
	 echo -e "\n";
	 echo "";
	 exit 1;;
    p|pmid)	
       wget -qO - https://www.bioinformatics.org/texmed/cgi-bin/list.cgi?PMID=$2 \
	  | sed -n '/<PRE>/,/<.PRE>/p' \
	  | sed -n '/@/,$p' \
	  | sed 's/<.PRE>//;x;1d'; 
	echo "";
	exit 1;;
    h|help|-h|--help)
        showhelp;exit 1;;
    --) 
       shift; break;;
    **)	
       exit 1;;
  esac
done
exit 1
